[theme]
base="light"
primaryColor="#5b0d8e"                 # stc purple
backgroundColor="#ffffff"              # white
secondaryBackgroundColor="#F3E9FB"     # light purple
textColor="#2B0A3D"                    # dark purple text
font="sans serif"
